### PR TITLE
general updates

### PR DESCRIPTION
**Pull request by A-Behairi**

### CODE REVIEW

**Review by lubojr — COMMENTED** [review]
I am receiving an error while trying to run `npm run start` after a fresh `npm install` on this PR from rollup using node 20
```
  [cause]: Error: Cannot find module '@rollup/rollup-linux-x64-gnu'
```
Is there anything I should address locally?

**Comment by A-Behairi** [comment]
I think it's caused by my laptop's arm CPU. try removing `package-lock.json` and reinstalling

**Comment by lubojr** [comment]
Okay, I tried that and got further but I am now getting
```
TypeError: Cannot read properties of undefined (reading 'split')
    at b (file:///home/lubomir/projects/gtif-cerulean-client/node_modules/@eodash/eodash/dist/node/cli.js:2:2569)
    at file:///home/lubomir/projects/gtif-cerulean-client/node_modules/@eodash/eodash/dist/node/cli.js:2:1567
```

Could you please advise what I could try?

**Comment by A-Behairi** [comment]
I'm not sure what could be causing this as well, but try updating your Node version to `^20.15.0` or Node 22

**Comment by lubojr** [comment]
Upgrading node 20 to latest worked. Thank you!

**Review by lubojr — APPROVED** [review]

**Pull request merged**
